#!/usr/bin/env bun
/**
 * mksprite.ts - Compile RGBA PNG to x86 compiled sprite for Watcom C++ / DOS
 *
 * Reads transparent-background PNG, maps colors to game palette,
 * generates x86 machine code (MOV instructions) for instant rendering.
 *
 * Usage:
 *   bun tools/mksprite.ts <image.png> <NAME> > SRC/SPR_NAME.H
 *   bun tools/mksprite.ts --test <NAME> > SRC/SPR_NAME.H
 *
 * Requires tools/palette.json (generated by mkpalette.ts).
 */

import { readFileSync, existsSync } from "fs";
import { parseArgs } from "util";

// ---- PNG reader (supports RGBA, RGB, Indexed+tRNS) ----

function paethPredictor(a: number, b: number, c: number): number {
  const p = a + b - c;
  const pa = Math.abs(p - a);
  const pb = Math.abs(p - b);
  const pc = Math.abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  if (pb <= pc) return b;
  return c;
}

function unfilterRow(
  filter: number, row: Uint8Array,
  prior: Uint8Array | null, bpp: number,
): void {
  switch (filter) {
    case 0: break;
    case 1: // Sub
      for (let i = bpp; i < row.length; i++)
        row[i] = (row[i] + row[i - bpp]) & 0xFF;
      break;
    case 2: // Up
      if (prior)
        for (let i = 0; i < row.length; i++)
          row[i] = (row[i] + prior[i]) & 0xFF;
      break;
    case 3: // Average
      for (let i = 0; i < row.length; i++) {
        const a = i >= bpp ? row[i - bpp] : 0;
        const b = prior ? prior[i] : 0;
        row[i] = (row[i] + ((a + b) >> 1)) & 0xFF;
      }
      break;
    case 4: // Paeth
      for (let i = 0; i < row.length; i++) {
        const a = i >= bpp ? row[i - bpp] : 0;
        const b = prior ? prior[i] : 0;
        const c = i >= bpp && prior ? prior[i - bpp] : 0;
        row[i] = (row[i] + paethPredictor(a, b, c)) & 0xFF;
      }
      break;
  }
}

function readPNG(path: string): { width: number; height: number; rgba: Uint8Array } {
  const buf = readFileSync(path);
  if (buf[0] !== 0x89 || buf[1] !== 0x50)
    throw new Error("Not a PNG file");

  let offset = 8;
  let width = 0, height = 0, bitDepth = 0, colorType = 0;
  const idatChunks: Buffer[] = [];
  let plte: Uint8Array | null = null;
  let trns: Uint8Array | null = null;

  while (offset < buf.length) {
    const length = buf.readUInt32BE(offset);
    const type = buf.toString("ascii", offset + 4, offset + 8);
    const data = buf.subarray(offset + 8, offset + 8 + length);

    if (type === "IHDR") {
      width = data.readUInt32BE(0);
      height = data.readUInt32BE(4);
      bitDepth = data[8];
      colorType = data[9];
    } else if (type === "PLTE") {
      plte = new Uint8Array(data);
    } else if (type === "tRNS") {
      trns = new Uint8Array(data);
    } else if (type === "IDAT") {
      idatChunks.push(Buffer.from(data));
    } else if (type === "IEND") {
      break;
    }
    offset += 12 + length;
  }

  if (bitDepth !== 8)
    throw new Error(`Only 8-bit PNG supported (got ${bitDepth}-bit)`);

  const bppMap: Record<number, number> = { 2: 3, 3: 1, 6: 4 };
  const bpp = bppMap[colorType];
  if (!bpp)
    throw new Error(`Unsupported color type ${colorType} (use RGB, RGBA, or indexed PNG)`);

  // Decompress and unfilter
  const compressed = Buffer.concat(idatChunks);
  // PNG IDAT uses zlib format (2-byte header + deflate + adler32)
  // Bun.inflateSync expects raw deflate, so strip the 2-byte zlib header
  const raw = Buffer.from(Bun.inflateSync(compressed.subarray(2)));
  const rowBytes = width * bpp;
  const pixels = new Uint8Array(height * rowBytes);
  let srcPos = 0;

  for (let y = 0; y < height; y++) {
    const filter = raw[srcPos++];
    const row = pixels.subarray(y * rowBytes, (y + 1) * rowBytes);
    const prior = y > 0 ? pixels.subarray((y - 1) * rowBytes, y * rowBytes) : null;
    for (let i = 0; i < rowBytes; i++) row[i] = raw[srcPos++];
    unfilterRow(filter, row, prior, bpp);
  }

  // Convert to RGBA
  const rgba = new Uint8Array(width * height * 4);

  if (colorType === 6) {
    rgba.set(pixels);
  } else if (colorType === 2) {
    for (let i = 0; i < width * height; i++) {
      rgba[i * 4] = pixels[i * 3];
      rgba[i * 4 + 1] = pixels[i * 3 + 1];
      rgba[i * 4 + 2] = pixels[i * 3 + 2];
      rgba[i * 4 + 3] = 255;
    }
  } else if (colorType === 3) {
    if (!plte) throw new Error("Indexed PNG missing PLTE chunk");
    for (let i = 0; i < width * height; i++) {
      const idx = pixels[i];
      rgba[i * 4] = plte[idx * 3];
      rgba[i * 4 + 1] = plte[idx * 3 + 1];
      rgba[i * 4 + 2] = plte[idx * 3 + 2];
      rgba[i * 4 + 3] = trns && idx < trns.length ? trns[idx] : 255;
    }
  }

  return { width, height, rgba };
}

// ---- palette matching ----

function loadPalette(): [number, number, number][] {
  const palPath = "tools/palette.json";
  if (!existsSync(palPath))
    throw new Error("tools/palette.json not found. Run: bun tools/mkpalette.ts");
  const data = JSON.parse(readFileSync(palPath, "utf-8"));
  return data.colors;
}

function nearestColor(
  r: number, g: number, b: number,
  palette: [number, number, number][],
): number {
  let bestIdx = 1;
  let bestDist = Infinity;
  // skip index 0 (transparent)
  for (let i = 1; i < palette.length; i++) {
    const dr = r - palette[i][0];
    const dg = g - palette[i][1];
    const db = b - palette[i][2];
    const dist = dr * dr + dg * dg + db * db;
    if (dist < bestDist) {
      bestDist = dist;
      bestIdx = i;
    }
  }
  return bestIdx;
}

function mapToIndexed(
  width: number, height: number, rgba: Uint8Array,
  palette: [number, number, number][],
): number[] {
  const pixels: number[] = new Array(width * height);
  for (let i = 0; i < width * height; i++) {
    const a = rgba[i * 4 + 3];
    if (a < 128) {
      pixels[i] = 0; // transparent
    } else {
      pixels[i] = nearestColor(
        rgba[i * 4], rgba[i * 4 + 1], rgba[i * 4 + 2], palette,
      );
    }
  }
  return pixels;
}

// ---- test sprite generator ----

function makeTestSprite(palette: [number, number, number][]): {
  w: number; h: number; pixels: number[];
} {
  const w = 16, h = 16, cx = 7, cy = 7;
  const pixels: number[] = [];
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const dist = Math.abs(x - cx) + Math.abs(y - cy);
      if (dist <= 6) {
        // cycle through first color ramp (red, index 16-31)
        pixels.push(16 + (dist % 16));
      } else {
        pixels.push(0);
      }
    }
  }
  return { w, h, pixels };
}

// ---- compiled sprite code gen ----

function compileSprite(
  w: number, h: number, pixels: number[],
  stride: number = 320,
): Uint8Array {
  const code: number[] = [];

  const pushLE32 = (v: number) => {
    code.push(v & 0xFF, (v >> 8) & 0xFF, (v >> 16) & 0xFF, (v >> 24) & 0xFF);
  };
  const pushLE16 = (v: number) => {
    code.push(v & 0xFF, (v >> 8) & 0xFF);
  };

  for (let y = 0; y < h; y++) {
    let x = 0;
    while (x < w) {
      if (pixels[y * w + x] === 0) { x++; continue; }

      const runStart = x;
      while (x < w && pixels[y * w + x] !== 0) x++;
      const runLen = x - runStart;

      const baseOff = y * stride + runStart;
      let pos = 0;
      while (pos < runLen) {
        const remaining = runLen - pos;
        const off = baseOff + pos;
        const idx = y * w + runStart + pos;

        if (remaining >= 4) {
          code.push(0xC7, 0x87);
          pushLE32(off);
          pushLE32(
            pixels[idx] | (pixels[idx + 1] << 8) |
            (pixels[idx + 2] << 16) | (pixels[idx + 3] << 24),
          );
          pos += 4;
        } else if (remaining >= 2) {
          code.push(0x66, 0xC7, 0x87);
          pushLE32(off);
          pushLE16(pixels[idx] | (pixels[idx + 1] << 8));
          pos += 2;
        } else {
          code.push(0xC6, 0x87);
          pushLE32(off);
          code.push(pixels[idx]);
          pos += 1;
        }
      }
    }
  }

  code.push(0xC3); // RET
  return new Uint8Array(code);
}

function formatCHeader(name: string, data: Uint8Array, w: number, h: number): string {
  const lines: string[] = [];
  lines.push(`#ifndef ${name}_H_INCLUDED`);
  lines.push(`#define ${name}_H_INCLUDED`);
  lines.push(``);
  lines.push(`#define ${name}_W ${w}`);
  lines.push(`#define ${name}_H ${h}`);
  lines.push(`#define ${name}_SIZE ${data.length}`);
  lines.push(``);
  lines.push(`unsigned char ${name.toLowerCase()}_code[] = {`);

  for (let i = 0; i < data.length; i += 12) {
    const chunk = Array.from(data.slice(i, i + 12));
    const hex = chunk.map((b) => `0x${b.toString(16).toUpperCase().padStart(2, "0")}`).join(", ");
    lines.push(i + 12 < data.length ? `    ${hex},` : `    ${hex}`);
  }

  lines.push(`};`);
  lines.push(``);
  lines.push(`#endif`);
  return lines.join("\n") + "\n";
}

function formatRawHeader(name: string, pixels: number[], w: number, h: number): string {
  const lines: string[] = [];
  lines.push(`#ifndef ${name}_H_INCLUDED`);
  lines.push(`#define ${name}_H_INCLUDED`);
  lines.push(``);
  lines.push(`#define ${name}_W ${w}`);
  lines.push(`#define ${name}_H ${h}`);
  lines.push(``);
  lines.push(`static unsigned char ${name.toLowerCase()}_data[] = {`);

  for (let i = 0; i < pixels.length; i += 16) {
    const chunk = pixels.slice(i, i + 16);
    const hex = chunk.map(b => `0x${b.toString(16).toUpperCase().padStart(2, "0")}`).join(", ");
    lines.push(i + 16 < pixels.length ? `    ${hex},` : `    ${hex}`);
  }

  lines.push(`};`);
  lines.push(``);
  lines.push(`#endif`);
  return lines.join("\n") + "\n";
}

function formatGridHeader(
  name: string,
  frames: { code: Uint8Array; w: number; h: number }[],
  frameW: number, frameH: number,
): string {
  const lines: string[] = [];
  const nameLower = name.toLowerCase();
  lines.push(`#ifndef ${name}_H_INCLUDED`);
  lines.push(`#define ${name}_H_INCLUDED`);
  lines.push(``);
  lines.push(`#define ${name}_W ${frameW}`);
  lines.push(`#define ${name}_H ${frameH}`);
  lines.push(`#define ${name}_FRAMES ${frames.length}`);
  lines.push(``);

  // Emit each frame's code array
  for (let i = 0; i < frames.length; i++) {
    const arrName = `${nameLower}_frame${i}_code`;
    lines.push(`static unsigned char ${arrName}[] = {`);
    const data = frames[i].code;
    for (let j = 0; j < data.length; j += 12) {
      const chunk = Array.from(data.slice(j, j + 12));
      const hex = chunk.map(b => `0x${b.toString(16).toUpperCase().padStart(2, "0")}`).join(", ");
      lines.push(j + 12 < data.length ? `    ${hex},` : `    ${hex}`);
    }
    lines.push(`};`);
    lines.push(``);
  }

  // Emit pointer array
  lines.push(`static unsigned char *${nameLower}_frames[] = {`);
  for (let i = 0; i < frames.length; i++) {
    const comma = i < frames.length - 1 ? "," : "";
    lines.push(`    ${nameLower}_frame${i}_code${comma}`);
  }
  lines.push(`};`);
  lines.push(``);
  lines.push(`#endif`);
  return lines.join("\n") + "\n";
}

// ---- main ----

const { values, positionals } = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    test: { type: "boolean", default: false },
    grid: { type: "string" },
    raw:  { type: "boolean", default: false },
  },
  allowPositionals: true,
});

let w: number, h: number, pixels: number[];

if (values.test) {
  if (positionals.length < 1) {
    console.error("Usage: bun mksprite.ts --test <NAME>");
    process.exit(1);
  }
  const palette = loadPalette();
  ({ w, h, pixels } = makeTestSprite(palette));
} else {
  if (positionals.length < 2) {
    console.error("Usage: bun mksprite.ts <image.png> <NAME>");
    console.error("       bun mksprite.ts --test <NAME>");
    process.exit(1);
  }
  const palette = loadPalette();
  const { width, height, rgba } = readPNG(positionals[0]);
  w = width;
  h = height;
  pixels = mapToIndexed(w, h, rgba, palette);
}

const name = positionals[values.test ? 0 : 1].toUpperCase();

if (values.raw) {
  // --raw mode: emit raw indexed pixels
  console.log(formatRawHeader(name, pixels, w, h));
  console.error(`/* ${w}x${h}, ${w * h} bytes raw */`);
} else if (values.grid) {
  // --grid mode: split into frames, compile each
  const [colStr, rowStr] = values.grid.split("x");
  const cols = parseInt(colStr, 10);
  const rows = parseInt(rowStr, 10);
  const frameW = Math.floor(w / cols);
  const frameH = Math.floor(h / rows);

  const frames: { code: Uint8Array; w: number; h: number }[] = [];
  for (let fy = 0; fy < rows; fy++) {
    for (let fx = 0; fx < cols; fx++) {
      const sub: number[] = [];
      for (let py = 0; py < frameH; py++) {
        for (let px = 0; px < frameW; px++) {
          sub.push(pixels[(fy * frameH + py) * w + (fx * frameW + px)]);
        }
      }
      frames.push({ code: compileSprite(frameW, frameH, sub), w: frameW, h: frameH });
    }
  }

  console.log(formatGridHeader(name, frames, frameW, frameH));
  console.error(`/* ${w}x${h} sheet, ${cols}x${rows} grid, ${frames.length} frames of ${frameW}x${frameH} */`);
} else {
  // Default mode: single compiled sprite (existing behavior)
  const code = compileSprite(w, h, pixels);
  console.log(formatCHeader(name, code, w, h));
  const opaque = pixels.filter(p => p !== 0).length;
  console.error(`/* ${w}x${h}, ${opaque} opaque px, ${code.length} bytes code */`);
}
