#!/usr/bin/env bun
/**
 * mktile.ts - Convert tileset PNG to binary .TIL format for DOS game
 *
 * Reads a tileset PNG (grid of tiles), maps colors to game palette,
 * outputs binary file with raw palette-indexed pixel data per tile.
 *
 * Format: uint32 tile_w, uint32 tile_h, uint32 num_tiles,
 *         then num_tiles * (tile_w * tile_h) bytes of indexed pixels.
 *
 * Usage:
 *   bun tools/mktile.ts <tileset.png> <OUTPUT.TIL> [--tw N] [--th N]
 *
 * Requires tools/palette.json (generated by mkpalette.ts).
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { parseArgs } from "util";

/* ---- PNG reader (reused from mksprite.ts) ---- */

function paethPredictor(a: number, b: number, c: number): number {
  const p = a + b - c;
  const pa = Math.abs(p - a);
  const pb = Math.abs(p - b);
  const pc = Math.abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  if (pb <= pc) return b;
  return c;
}

function unfilterRow(
  filter: number, row: Uint8Array,
  prior: Uint8Array | null, bpp: number,
): void {
  switch (filter) {
    case 0: break;
    case 1:
      for (let i = bpp; i < row.length; i++)
        row[i] = (row[i] + row[i - bpp]) & 0xFF;
      break;
    case 2:
      if (prior)
        for (let i = 0; i < row.length; i++)
          row[i] = (row[i] + prior[i]) & 0xFF;
      break;
    case 3:
      for (let i = 0; i < row.length; i++) {
        const a = i >= bpp ? row[i - bpp] : 0;
        const b = prior ? prior[i] : 0;
        row[i] = (row[i] + ((a + b) >> 1)) & 0xFF;
      }
      break;
    case 4:
      for (let i = 0; i < row.length; i++) {
        const a = i >= bpp ? row[i - bpp] : 0;
        const b = prior ? prior[i] : 0;
        const c = i >= bpp && prior ? prior[i - bpp] : 0;
        row[i] = (row[i] + paethPredictor(a, b, c)) & 0xFF;
      }
      break;
  }
}

function readPNG(path: string): { width: number; height: number; rgba: Uint8Array } {
  const buf = readFileSync(path);
  if (buf[0] !== 0x89 || buf[1] !== 0x50)
    throw new Error("Not a PNG file");

  let offset = 8;
  let width = 0, height = 0, bitDepth = 0, colorType = 0;
  const idatChunks: Buffer[] = [];
  let plte: Uint8Array | null = null;
  let trns: Uint8Array | null = null;

  while (offset < buf.length) {
    const length = buf.readUInt32BE(offset);
    const type = buf.toString("ascii", offset + 4, offset + 8);
    const data = buf.subarray(offset + 8, offset + 8 + length);

    if (type === "IHDR") {
      width = data.readUInt32BE(0);
      height = data.readUInt32BE(4);
      bitDepth = data[8];
      colorType = data[9];
    } else if (type === "PLTE") {
      plte = new Uint8Array(data);
    } else if (type === "tRNS") {
      trns = new Uint8Array(data);
    } else if (type === "IDAT") {
      idatChunks.push(Buffer.from(data));
    } else if (type === "IEND") {
      break;
    }
    offset += 12 + length;
  }

  if (bitDepth !== 8)
    throw new Error(`Only 8-bit PNG supported (got ${bitDepth}-bit)`);

  const bppMap: Record<number, number> = { 2: 3, 3: 1, 6: 4 };
  const bpp = bppMap[colorType];
  if (!bpp)
    throw new Error(`Unsupported color type ${colorType}`);

  const compressed = Buffer.concat(idatChunks);
  const raw = Buffer.from(Bun.inflateSync(compressed.subarray(2)));
  const rowBytes = width * bpp;
  const pixels = new Uint8Array(height * rowBytes);
  let srcPos = 0;

  for (let y = 0; y < height; y++) {
    const filter = raw[srcPos++];
    const row = pixels.subarray(y * rowBytes, (y + 1) * rowBytes);
    const prior = y > 0 ? pixels.subarray((y - 1) * rowBytes, y * rowBytes) : null;
    for (let i = 0; i < rowBytes; i++) row[i] = raw[srcPos++];
    unfilterRow(filter, row, prior, bpp);
  }

  const rgba = new Uint8Array(width * height * 4);
  if (colorType === 6) {
    rgba.set(pixels);
  } else if (colorType === 2) {
    for (let i = 0; i < width * height; i++) {
      rgba[i * 4] = pixels[i * 3];
      rgba[i * 4 + 1] = pixels[i * 3 + 1];
      rgba[i * 4 + 2] = pixels[i * 3 + 2];
      rgba[i * 4 + 3] = 255;
    }
  } else if (colorType === 3) {
    if (!plte) throw new Error("Indexed PNG missing PLTE chunk");
    for (let i = 0; i < width * height; i++) {
      const idx = pixels[i];
      rgba[i * 4] = plte[idx * 3];
      rgba[i * 4 + 1] = plte[idx * 3 + 1];
      rgba[i * 4 + 2] = plte[idx * 3 + 2];
      rgba[i * 4 + 3] = trns && idx < trns.length ? trns[idx] : 255;
    }
  }

  return { width, height, rgba };
}

/* ---- palette matching ---- */

function loadPalette(): [number, number, number][] {
  const palPath = "tools/palette.json";
  if (!existsSync(palPath))
    throw new Error("tools/palette.json not found. Run: bun tools/mkpalette.ts");
  return JSON.parse(readFileSync(palPath, "utf-8")).colors;
}

function nearestColor(
  r: number, g: number, b: number,
  palette: [number, number, number][],
): number {
  let bestIdx = 1;
  let bestDist = Infinity;
  for (let i = 1; i < palette.length; i++) {
    const dr = r - palette[i][0];
    const dg = g - palette[i][1];
    const db = b - palette[i][2];
    const dist = dr * dr + dg * dg + db * db;
    if (dist < bestDist) { bestDist = dist; bestIdx = i; }
  }
  return bestIdx;
}

/* ---- main ---- */

const { values, positionals } = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    tw: { type: "string", default: "16" },
    th: { type: "string", default: "16" },
  },
  allowPositionals: true,
});

if (positionals.length < 2) {
  console.error("Usage: bun tools/mktile.ts <tileset.png> <OUTPUT.TIL> [--tw N] [--th N]");
  process.exit(1);
}

const tileW = parseInt(values.tw!, 10);
const tileH = parseInt(values.th!, 10);
const palette = loadPalette();
const { width, height, rgba } = readPNG(positionals[0]);

const cols = Math.floor(width / tileW);
const rows = Math.floor(height / tileH);
const numTiles = cols * rows;

console.error(`Tileset: ${width}x${height}, ${cols}x${rows} grid, ${numTiles} tiles of ${tileW}x${tileH}`);

const tileSize = tileW * tileH;
const dataSize = 12 + numTiles * tileSize;
const buf = Buffer.alloc(dataSize);

buf.writeUInt32LE(tileW, 0);
buf.writeUInt32LE(tileH, 4);
buf.writeUInt32LE(numTiles, 8);

let off = 12;
for (let ty = 0; ty < rows; ty++) {
  for (let tx = 0; tx < cols; tx++) {
    for (let py = 0; py < tileH; py++) {
      for (let px = 0; px < tileW; px++) {
        const sx = tx * tileW + px;
        const sy = ty * tileH + py;
        const i = (sy * width + sx) * 4;
        const a = rgba[i + 3];
        if (a < 128) {
          buf[off++] = 0;
        } else {
          buf[off++] = nearestColor(rgba[i], rgba[i + 1], rgba[i + 2], palette);
        }
      }
    }
  }
}

writeFileSync(positionals[1], buf);
console.error(`Wrote ${positionals[1]}: ${dataSize} bytes, ${numTiles} tiles`);
